name: Docker Image CD

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check Docker status
        run: sudo systemctl status docker

      - name: Pull Docker image
        run: docker pull umerali5745/cicd_pipeline:latest

      - name: Check if Docker container exists
        run: |
          docker ps -a --filter "name=cicd_pipeline-container"

      - name: Delete old Docker container if exists
        run: |
          if docker ps -a --filter "name=cicd_pipeline-container" -q; then
            echo "Container exists, removing...";
            sudo docker rm -f cicd_pipeline-container;
          else
            echo "Container not found, skipping removal.";
          fi

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name cicd_pipeline-container umerali5745/cicd_pipeline:latest
